#!/bin/bash

venv_dir="./.venv"

[ ! -d "$venv_dir" ] && python3 -m venv $venv_dir
source $venv_dir/bin/activate
if [[ "$(find $venv_dir -type d -name pygame)" != *pygame* ]]; then
  pip install pygame
fi
deactivate
